### ISSUE TITLE
    connection = sqlite3.connect(_DB_path) sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by 000KeyserSoze000** [914alexwillett/StochRSI-Crypto-Trading-Algorithm#1]
Hello, congratualtaions.
in create database:

import sqlite3
# desired filepath for database
path = r'C:\Program Files\Python310\Lib\trade_database.db'
--------------------------------
>>> 
*** Remote Interpreter Reinitialized ***
Trade database created
>>> 
After i have a bug, when i launch tradebot.py

*** Remote Interpreter Reinitialized ***
Traceback (most recent call last):
  File "C:\Users\Flo\Desktop\StochRSI-Crypto-Trading-Algorithm-main\tradebot.py", line 36, in <module>
    eth_update, ETH_df = update_class.get_up_to_date(update_class, path, 2)
  File "C:\Users\Flo\Desktop\StochRSI-Crypto-Trading-Algorithm-main\trade_functions.py", line 105, in get_up_to_date
    connection = sqlite3.connect(_DB_path)
sqlite3.OperationalError: unable to open database file
>>>

**Comment by 000KeyserSoze000** [comment]
Sorry, all its ok but i have this message when i launch the bot
 File "C:\Program Files\Python310\lib\site-packages\pandas\core\internals\base.py", line 57, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 2 elements
